### ISSUE TITLE
'_dynet.ParameterCollection' object has no attribute 'load'

### ISSUE THREAD

**Issue by brombach** [elikip/bist-parser#15]
Hello,
I am trying to use this parser in conjunction with NLP4J and PathLSTM. NLP4J has outputted a this file:
```
1	Michael	michael	NNP	_	_	_	_	@#r$%
2	Jordan	jordan	NNP	_	_	_	_	@#r$%
3	played	play	VBD	_	_	_	_	@#r$%
4	basketball	basketball	NN	_	_	_	_	@#r$%
5	in	in	IN	_	_	_	_	@#r$%
6	Chicago	chicago	NNP	_	_	_	_	@#r$%
7	.	.	.	_	_	_	_	@#r$%
```
I'm not sure why the last column is the way it is, but I also tried removing it and ran into the same problem:
Upon running
```
python bist-parser/bmstparser/src/parser.py --predict --outdir out --test sentences.conll  --model bist-parser/bmstparser/model/bestfirstorder.model --params bist-parser/bmstparser/model/bestfirstorder.params
```
(using the model and params from the readme)

I get this output and error:
```
[dynet] random seed: 161569565
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
Using external embedding: None
Initializing lstm mstparser:
Traceback (most recent call last):
  File "bist-parser/bmstparser/src/parser.py", line 45, in <module>
    parser.Load(options.model)
  File "/PathLSTM/bist-parser/bmstparser/src/mstlstm.py", line 139, in Load
    self.model.load(filename)
AttributeError: '_dynet.ParameterCollection' object has no attribute 'load'
```

Any suggestions would be appreciated. Thanks!

**Comment by elikip** [comment]
Hi, dynet was upgraded to v2.0 (about a week ago) which is not backward compatible with v1.1 that I was using. Please checkout the old dynet version instead (checkout their v1.1 branch instead of master). The code should be working with the old dynet version.

**Comment by BhaskarNallani** [comment]
Hi,
Is there any plan to support Dynet v2.0?
Thanks & Regards,
Bhaskar

**Comment by brombach** [comment]
@elikip It seems that neither the 1.1 branch directly off of GitHub nor the newly released pip install of v1.1 work with bist-parser. I've tried with both and get this error:
```
root@a6ba7c6b3564:/bist-parser/barchybrid# python src/parser.py --predict --outdir out --test lines.conll09 --extrn sskip.100.vectors --model model/bestarchybrid.model --params model/bestarchybrid.params 
[dynet] random seed: 1477609549
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
Using external embedding: sskip.100.vectors
Load external embedding. Vector dimensions 100
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  unsupported version
Aborted
```

**Comment by BhaskarNallani** [comment]
Hi,
I am able to run the parser with v1.1 dynet branch with cuDNNV5.1 and with out CUDA backup also.
The issue is in the model file  barchybrid.model  which is dumped with different version of boost and dynet v1.1 is compatible with boost_1_63_0 only (this if figured it out with after experimenting with 1.58,1.63 and 1.64). I gain ran the training on the development.conll data for 30 epochs and used the generated model for inference. I know this may not perform well on the new data because of less input data to trainer. But my object is not the accuracy here but accelerating it.
-Bhaskar

**Comment by peteruhrig** [comment]
I ran into the same problems on Ubuntu 16.04 LTS
Just to make it explicit, the first can be resolved by running this:
```
apt-get install libboost-all-dev
pip install git+https://github.com/clab/dynet@v1.1#egg=dynet
```
However, that did not get me very far. I now get the following error:
```
python src/parser.py --predict --outdir ~ --test ~/test.tsv --model ../model/bestfirstorder.model --params ../model/bestfirstorder.params
[dynet] random seed: 1495272741
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
Using external embedding: None
Initializing lstm mstparser:
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  input stream error
Aborted
```

For the archybrid parser, I get the same errors as brombach (unsupported version)

@BhaskarNallani: Since I do not have the training files, I need to rely on the released model. If you have a pointer as to where the training files are available, I'd of course be interested!

@elikip: At the moment I cannot confirm that the code works with the old dynet version. To me it looks as if the parsers have become unusable in Ubuntu 16.04 LTS.
I also tried Ubuntu 14.04 LTS, 15.04, and 15.10, hoping that the problem may go away with an older version of Boost. However, neither of these lets me install dynet 1.1 because of some version incompatibility.

Best,
Peter

**Comment by elikip** [comment]
Sorry for the delayed response, unfortunately my availability at the moment is limited.
Regarding the new dynet version: 
I plan to the parser compatible with the new dynet version. Its the second time this year that dynet released a major version which not backward compatible to previous version. I have adjusted the parser to support the previous version and I hope to do this for version too.
Regrading the pretrained models:
It seems like an incompatible boost version. You could try to train your own parser models using the freely available universal dependencies data. This problem will not happen once I upgrade the code to the new dynet version, since that version does not use boost as far as I know.

I hope this helps,
Eli.

**Comment by Cocophotos** [comment]
Hi all,

I've submitted a pull request (#17) that should work with DyNet 2.0. The best models are available upon request.

Best regards,
-- 
Corentin

**Comment by heejincs** [comment]
Hi,

 where can I get the best model? Thank you very much!


Sincerely,
 Heejin
