### ISSUE TITLE
Get an error: _dynet.pyx NotImplementedError

### ISSUE THREAD

**Issue by Samurais** [elikip/bist-parser#23]
hi, folks

Could anyone help?  I use such cmd for training
```
dynetSeed=123321889
dynetMem=1024 # MB
outdir=$baseDir/../../save/barchybrid
trainData=$baseDir/../../data/CDT/dependency/CDT.dev.conllu
testData=$baseDir/../../data/CDT/dependency/CDT.test.conllu
epochs=30
lstmdims=100
lstmlayers=2
embedding=$baseDir/../../data/word2vec/news.w2v.vectors

# functions

# main
[ -z "${BASH_SOURCE[0]}" -o "${BASH_SOURCE[0]}" = "$0" ] || return
cd $baseDir/..
python src/parser.py \
    --dynet-seed $dynetSeed \
    --dynet-mem $dynetMem \
    --outdir $outdir \
    --train $trainData \
    --dev $testData \
    --epochs $epochs \
    --lstmdims $lstmdims \
    --lstmlayers $lstmlayers \
    --extrn $embedding \
    --bibi-lstm \
    --usehead
```

I come to the following error

```
[dynet] random seed: 123321889
[dynet] allocating memory: 1024MB
[dynet] memory allocation done.
Using external embedding: bist-parser/barchybrid/admin/../../data/word2vec/news.w2v.vectors
Preparing vocab
0 dropped non-projective sentences.
59905 sentences read.
Finished collecting vocab
Initializing blstm arc hybrid:
Load external embedding. Vector dimensions 100
Starting epoch 0
0 dropped non-projective sentences.
59905 sentences read.
Traceback (most recent call last):
  File "src/parser.py", line 55, in <module>
    parser.Train(options.conll_train)
  File "bist-parser/barchybrid/src/arc_hybrid.py", line 296, in Train
    self.Init()
  File "bist-parser/barchybrid/src/arc_hybrid.py", line 165, in Init
    paddingVec = tanh(self.word2lstm.expr() * concatenate(filter(None, [paddingWordVec, paddingPosVec, evec])) + self.word2lstmbias.expr() )
  File "_dynet.pyx", line 853, in _dynet.Expression.__mul__
NotImplementedError
```

Code 4cd6a29d6c737ff29cb61c0e51532a9d60c4818c

Python and dynet
![image](https://user-images.githubusercontent.com/3538629/39623477-53afc10c-4fc8-11e8-9cca-057aca96af70.png)

**Comment by Samurais** [comment]
Now it works
![image](https://user-images.githubusercontent.com/3538629/39629793-f3b66f0e-4fdf-11e8-8a77-67c173f26f0b.png)

Just use dynet v1.
```
 pip install dyNET==1.1.0
``` 

Thanks for @elikip, answer via email.
